shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    get '/variants/search', to: "variants#search", as: :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_authorization_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :tax_rates

    resources :trackers
    resources :payment_methods
    resources :roles

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
    end
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/controllers/spree/admin/option_types_controller.rb
module Spree
  module Admin
    class OptionTypesController < ResourceController
      before_action :setup_new_option_value, only: :edit

      def update_values_positions
        ActiveRecord::Base.transaction do
          params[:positions].each do |id, index|
            Spree::OptionValue.where(id: id).update_all(position: index)
          end
        end

        respond_to do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js { render text: 'Ok' }
        end
      end

      protected

        def location_after_save
          if @option_type.created_at == @option_type.updated_at
            edit_admin_option_type_url(@option_type)
          else
            admin_option_types_url
          end
        end


      private
        def load_product
          @product = Product.find_by_param!(params[:product_id])
        end

        def setup_new_option_value
          @option_type.option_values.build if @option_type.option_values.empty?
        end

        def set_available_option_types
          @available_option_types = if @product.option_type_ids.any?
            OptionType.where('id NOT IN (?)', @product.option_type_ids)
          else
            OptionType.all
          end
        end
    end
  end
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/option_types/_form.html.erb
<div data-hook="admin_option_type_form_fields" class="row">
  <div class="col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => "form-control" %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :presentation, class: ['form-group'] do %>
      <%= f.label :presentation, Spree.t(:presentation) %> <span class="required">*</span>
      <%= f.text_field :presentation, :class => "form-control" %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
</div>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/option_types/_option_value_fields.html.erb
<tr class="option_value fields" id="spree_<%= dom_id(f.object) %>" data-hook="option_value">
  <td class="move-handle text-center">
    <span class="icon icon-move handle"></span>
    <%= f.hidden_field :id %>
  </td>
  <td class="name"><%= f.text_field :name, class: "form-control" %></td>
  <td class="presentation"><%= f.text_field :presentation, class: "form-control" %></td>
  <td class="actions actions-1 text-center"><%= link_to_icon_remove_fields f %></td>
</tr>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/option_types/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::OptionType.model_name.human) %> <span class="green">"<%= @option_type.name %>"</span>
<% end %>

<% content_for :page_actions do %>
  <span id="new_add_option_value" data-hook>
    <%= button_link_to Spree.t(:add_option_value), "javascript:;", { :icon => 'add', :'data-target' => "tbody#option_values", :class => 'btn-success spree_add_fields' } %>
  </span>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @option_type } %>

<%= form_for [:admin, @option_type] do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= Spree.t(:option_values) %>
      </h1>
    </div>
    <div class="panel-body">
      <%= render :partial => 'form', :locals => { :f => f } %>
    </div>
    <table class="table table-condensed table-bordered sortable" data-hook data-sortable-link="<%= update_values_positions_admin_option_types_url %>">
      <thead data-hook="option_header">
        <tr>
          <th colspan="2"><%= Spree.t(:name) %></th>
          <th><%= Spree.t(:display) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="option_values">
        <% if @option_type.option_values.empty? %>
          <tr id="none" data-hook="option_none">
            <td colspan="2"><%= Spree.t(:none) %></td>
            <td class="actions text-center"></td>
          </tr>
        <% else %>
          <%= f.fields_for :option_values do |option_value_form| %>
            <%= render :partial => 'option_value_fields', :locals => { :f => option_value_form } %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="panel-footer text-center">
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </div>
  </div>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/option_types/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::OptionType) %>
<% end %>

<% content_for :page_actions do %>
  <span id="new_ot_link">
    <%= button_link_to Spree.t(:new_option_type), new_object_url, { class: "btn-success", icon: 'add', id: 'new_option_type_link' } %>
  </span>
<% end %>

<div id="new_option_type"></div>

<% if @option_types.any? %>
<table class="table sortable" id="listing_option_types" data-hook data-sortable-link="<%= update_positions_admin_option_types_url %>">
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:presentation) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @option_types.each do |option_type| %>
      <tr class="spree_option_type <%= cycle('odd', 'even')%>" id="<%= spree_dom_id option_type %>" data-hook="option_row">
        <td class="move-handle text-center">
          <span class="icon icon-move handle"></span>
        </td>
        <td><%= option_type.name %></td>
        <td class="presentation"><%= option_type.presentation %></td>
        <td class="actions actions-2 text-right">
          <%= link_to_edit(option_type, class: 'admin_edit_option_type', no_text: true) %>
          <%= link_to_delete(option_type, no_text: true) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::OptionType)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/option_types/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_option_type) %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @option_type } %>

<%= form_for [:admin, @option_type] do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>