shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    get '/variants/search', to: "variants#search", as: :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_authorization_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :tax_rates

    resources :trackers
    resources :payment_methods
    resources :roles

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
    end
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/controllers/spree/admin/stock_movements_controller.rb
module Spree
  module Admin
    class StockMovementsController < Spree::Admin::BaseController
      respond_to :html
      helper_method :stock_location

      def index
        @stock_movements = stock_location.stock_movements.recent.
          includes(:stock_item => { :variant => :product }).
          page(params[:page])
      end

      def new
        @stock_movement = stock_location.stock_movements.build
      end

      def create
        @stock_movement = stock_location.stock_movements.build(stock_movement_params)
        @stock_movement.save
        flash[:success] = flash_message_for(@stock_movement, :successfully_created)
        redirect_to admin_stock_location_stock_movements_path(stock_location)
      end

      def edit
        @stock_movement = StockMovement.find(params[:id])
      end

      private

      def stock_location
        @stock_location ||= StockLocation.find(params[:stock_location_id])
      end

      def stock_movement_params
        params.require(:stock_movement).permit(:quantity, :stock_item_id, :action)
      end
    end
  end
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/helpers/spree/admin/stock_movements_helper.rb
module Spree
  module Admin
    module StockMovementsHelper
      def pretty_originator(stock_movement)
        if stock_movement.originator.respond_to?(:number)
          if stock_movement.originator.respond_to?(:order)
            link_to stock_movement.originator.number, [:edit, :admin, stock_movement.originator.order]
          else
            stock_movement.originator.number
          end
        else
          ""
        end
      end

      def display_variant(stock_movement)
        variant = stock_movement.stock_item.variant
        output = variant.name
        output += "<br>(#{variant.options_text})" unless variant.options_text.blank?
        output.html_safe
      end
    end
  end
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/stock_movements/_form.html.erb
<div data-hook="admin_stock_movements_form_fields">
  <%= f.field_container :quantity, class: ['form-group'] do %>
    <%= f.label :quantity, Spree.t(:quantity) %>
    <%= f.text_field :quantity %>
  <% end %>
  <%= f.field_container :stock_item_id, class: ['form-group'] do %>
    <%= f.label :stock_item_id, Spree.t(:stock_item_id) %>
    <%= f.text_field 'stock_item_id', :class => 'form-control', :'data-stock-location-id' => params[:stock_location_id] %>
  <% end %>
</div>

<%= render :partial => "spree/admin/variants/autocomplete", :formats => :js %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/stock_movements/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::StockMovement.model_name.human) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_resource_list, resource: Spree::StockMovement.model_name.human), admin_stock_location_stock_movements_path(stock_location), class: 'btn btn-default' %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @stock_movement } %>

<%= form_for [:admin, stock_location, @stock_movement] do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links', locals: { collection_url: admin_stock_location_stock_movements_path(stock_location) } %>
  </fieldset>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/stock_movements/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:stock_movements_for_stock_location, stock_location_name: @stock_location.name) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_stock_movement), new_admin_stock_location_stock_movement_path(@stock_location), icon: 'plus', id: 'admin_new_stock_movement_link' %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_resource_list, resource: Spree::StockLocation.model_name.human), admin_stock_locations_path, class: 'btn btn-default' %>
<% end %>

<% if @stock_movements.any? %>
<table class="table" id='listing_stock_movements'>
  <colgroup>
    <col style="width: 35%">
    <col style="width: 20%">
    <col style="width: 45%">
  </colgroup>
  <thead>
    <tr data-hook="admin_stock_movements_index_headers">
      <th><%= Spree.t(:stock_item) %>
      <th><%= Spree.t(:quantity) %></th>
      <th><%= Spree.t(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <% @stock_movements.each do |stock_movement|%>
      <tr id="<%= spree_dom_id stock_movement %>" data-hook="admin_stock_movements_index_rows">
        <td>
          <%= display_variant(stock_movement) %>
        </td>
        <td><%= stock_movement.quantity %></td>
        <td><%= pretty_originator(stock_movement) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::StockMovement)) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_stock_location_stock_movement_path(@stock_location) %>!
  </div>
<% end %>

<%= paginate @stock_movements %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/stock_movements/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_stock_movement) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t(:back_to_stock_movements_list), admin_stock_location_stock_movements_path(stock_location), :class => 'btn btn-default' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @stock_movement } %>

<%= form_for [:admin, stock_location, @stock_movement] do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links', locals: { collection_url: admin_stock_location_stock_movements_path(stock_location) } %>
  </fieldset>
<% end %>