shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    get '/variants/search', to: "variants#search", as: :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_authorization_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :tax_rates

    resources :trackers
    resources :payment_methods
    resources :roles

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
    end
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/controllers/spree/admin/variants_controller.rb
module Spree
  module Admin
    class VariantsController < ResourceController
      belongs_to 'spree/product', :find_by => :slug
      new_action.before :new_before
      before_action :load_data, only: [:new, :create, :edit, :update]

      # override the destroy method to set deleted_at value
      # instead of actually deleting the product.
      def destroy
        @variant = Variant.find(params[:id])
        if @variant.destroy
          flash[:success] = Spree.t('notice_messages.variant_deleted')
        else
          flash[:success] = Spree.t('notice_messages.variant_not_deleted')
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js  { render_js_for_destroy }
        end
      end

      protected
        def new_before
          @object.attributes = @object.product.master.attributes.except('id', 'created_at', 'deleted_at',
                                                                        'sku', 'is_master')
          # Shallow Clone of the default price to populate the price field.
          @object.default_price = @object.product.master.default_price.clone
        end

        def collection
          @deleted = (params.key?(:deleted) && params[:deleted] == "on") ? "checked" : ""

          if @deleted.blank?
            @collection ||= super.includes(:default_price, option_values: :option_type)
          else
            @collection ||= Variant.only_deleted.where(:product_id => parent.id)
          end
          @collection
        end

      private
        def load_data
          @tax_categories = TaxCategory.order(:name)
        end
    end
  end
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/_autocomplete.js.erb
<script type='text/template' id='variant_autocomplete_template'>
  <div class='variant-autocomplete-item media'>
    <figure class='variant-image media-left'>
      <span class="thumbnail no-marginb">
        {{#if variant.image }}
          <img src='{{variant.image}}' />
        {{ else }}
          <img src='<%= image_path("noimage/mini.png") %>' />
        {{/if}}
      </span>
    </figure>

    <div class='variant-details media-body'>
      <h5 class="variant-name media-heading">{{variant.name}}</h5>
      {{#if variant.option_values}}
        {{#each variant.option_values}}
          <strong>{{this.option_type_presentation}}:</strong> {{this.presentation}}<br/>
        {{/each}}
      {{/if}}
      <strong><%= Spree.t(:sku) %>:</strong> {{variant.sku}}
    </div>
  </div>
</script>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/_autocomplete_line_items_stock.js.erb
<script type='text/template' id='variant_line_items_autocomplete_stock_template'>
  
  <label><%= Spree.t(:select_stock) %></label>

  <table class="stock-levels table table-bordered" data-hook="stock-levels">
    <thead>
      <th><%= Spree.t(:name) %></th>
      <th class="text-center"><%= Spree.t(:count_on_hand) %></th>
      <th class="text-center"><%= Spree.t(:quantity) %></th>
      <th></th>
    </thead>
    <tbody>
      <tr>
        <td>{{variant.name}}</td>
        {{#if variant.track_inventory}}
          {{#if variant.total_on_hand}}
            <td class="text-center">{{variant.total_on_hand}}</td>
            <td class="text-center">
              <input class="quantity form-control" id="variant_quantity" data-variant-id="{{variant.id}}" type="number" min="1" value="1">
            </td>
            <td class="actions actions-1 text-center">
              <button class="btn btn-sm btn-success add_variant with-tip" data-variant-id="{{variant.id}}" title="<%= Spree.t(:add) %>" data-action="add">
                <span class="icon icon-add"></span>
                </button>
            </td>
          {{else}}
            <td class="text-center"><%= Spree.t(:out_of_stock) %></td>
            <td class="text-center">0</td>
            <td></td>
            <td></td>
          {{/if}}
        {{else}}
          <td class="text-center"><%= Spree.t(:doesnt_track_inventory) %></td>
          <td class="text-center">
            <input class="quantity form-control" id="variant_quantity" data-variant-id="{{variant.id}}" type="number" min="1" value="1">
          </td>
          <td class="actions actions-1 text-center">
            <button class="btn btn-sm btn-success add_variant with-tip" data-variant-id="{{variant.id}}" title="<%= Spree.t(:add) %>" data-action="add">
              <span class="icon icon-add"></span>
            </button>
          </td>
        {{/if}}
      </tr>
    </tbody>
  </table>
</script>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/_autocomplete_stock.js.erb
<script type='text/template' id='variant_autocomplete_stock_template'>
  
  <label><%= Spree.t(:select_stock) %></label>
  <table class="table table-condensed table-bordered stock-levels no-marginb" data-hook="stock-levels">
    <thead>
      <th><%= Spree.t(:location) %></th>
      <th><%= Spree.t(:count_on_hand) %></th>
      <th width="15%"><%= Spree.t(:quantity) %></th>
      <th class="actions"></th>
    </thead>
    <tbody>
      {{#each variant.stock_items}}
        <tr>
          <td>{{this.stock_location_name}}</td>
          {{#unless ../variant.track_inventory}}
            <td>It doesn't track inventory</td>
            <td>
              <input class="quantity form-control input-sm" id="stock_item_quantity" data-stock-location-id="{{this.stock_location_id}}" type="number" min="1" value="1">
            </td>
            <td class="actions actions-1">
              <button class="btn btn-sm btn-default add_variant with-tip" data-stock-location-id="{{this.stock_location_id}}" title="<%= Spree.t(:add) %>" data-action="add">
                <span class="icon icon-add"></span>
              </button>
            </td>
          {{else}}
            {{#if this.available}}
              <td>
                {{this.count_on_hand}}
                {{#if this.backorderable}} (<%= Spree.t(:backorders_allowed) %>) {{/if}}
              </td>
              <td>
                <input class="quantity form-control input-sm" id="stock_item_quantity" data-stock-location-id="{{this.stock_location_id}}" type="number" min="1" value="1">
              </td>
              <td class="actions actions-1">
                <button class="btn btn-sm btn-default add_variant with-tip" data-stock-location-id="{{this.stock_location_id}}" title="<%= Spree.t(:add) %>" data-action="add">
                  <span class="icon icon-add"></span>
                </button>
              </td>
            {{else}}
              <td><%= Spree.t(:out_of_stock) %></td>
              <td>0</td>
            {{/if}}
          {{/unless}}
        </tr>
      {{/each}}
    </tbody>
  </table>  
</script>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/_form.html.erb
<div class="row">
  <div data-hook="admin_variant_form_fields" class="col-md-6">
    <div data-hook="variants">
      <% @product.option_types.each do |option_type| %>
        <div class="form-group" data-hook="presentation">
          <%= label :new_variant, option_type.presentation %>
          <%= f.collection_select 'option_value_ids', option_type.option_values, :id, :presentation,
            { :prompt => true }, { :name => 'variant[option_value_ids][]', :class => 'select2' } %>
        </div>
      <% end %>

      <div class="form-group" data-hook="sku">
        <%= f.label :sku, Spree.t(:sku) %>
        <%= f.text_field :sku, :class => 'form-control' %>
      </div>

      <div class="form-group" data-hook="price">
        <%= f.label :price, Spree.t(:price) %>
        <%= f.text_field :price, :value => number_to_currency(@variant.price, :unit => ''), :class => 'form-control' %>
      </div>

      <div class="form-group" data-hook="cost_price">
        <%= f.label :cost_price, Spree.t(:cost_price) %>
        <%= f.text_field :cost_price, :value => number_to_currency(@variant.cost_price, :unit => ''), :class => 'form-control' %>
      </div>

      <div class="form-group" data-hook="tax_category">
        <%= f.label :tax_category_id, Spree.t(:tax_category) %>
        <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2' }) %>
      </div>
    </div>
  </div>

  <div class="col-md-6" data-hook="admin_variant_form_additional_fields">
    <% [:weight, :height, :width, :depth].each do |field| %>
      <div class="form-group" data-hook="<%= field %>"><%= f.label field, Spree.t(field) %>
        <% value = number_with_precision(@variant.send(field), :precision => 2) %>
        <%= f.text_field field, :value => value, :class => 'form-control' %>
      </div>
    <% end %>
  </div>
</div>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/_split.js.erb
<script type='text/template' id='variant_split_template'>
  <tr class='stock-item-split' data-variant-id='{{variant.id}}'>
    <td colspan='2'>
      <%= Spree.t("move_variant_to", default: "Move {{variant.name}} to") %>
    </td>
    <td colspan='2'>
    <select name="item_stock_location" id='item_stock_location' style='width:100%;'>
      <option></option>
      <optgroup label="<%=Spree.t('existing_shipments')%>">
        {{#each shipments}}
        <option data-shipment-number='{{this.number}}' value='{{this.stock_location_id}}'>{{this.stock_location.name}}({{this.number}})</option>
        {{/each}}
      </optgroup>
      <optgroup label="<%=Spree.t('new_shipment_at_location')%>">
        {{#each variant.stock_items}}
          <option data-new-shipment='true' value='{{this.stock_location_id}}'>{{this.stock_location_name}}&nbsp({{this.count_on_hand}} on hand)</option>
        {{/each}}
      </optgroup>
      </select>
    </td>
    <td>
      <input class="quantity form-control" id="item_quantity" type="number" min="1" value="1" max="{{max_quantity}}">
    </td>
    <td class='actions'>
      <a href='#' class='cancel-split with-tip btn btn-sm btn-default' title='Cancel'>
        <span class="icon icon-arrow-left"></span>
      </a>
      <a href='#' class='save-split with-tip btn btn-sm btn-success' title='Save'>
        <span class="icon icon-save"></span>
      </a>
    </td>
  </tr>
</script>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Variants' } %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset>
    <div data-hook="admin_variant_edit_form">
      <%= render :partial => 'form', :locals => { :f => f } %>
    </div>

    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/index.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Variants'} %>

<%# Place for new variant form %>
<div id="new_variant" data-hook></div>

<% if @variants.any? %>
  <table class="table sortable" data-sortable-link="<%= update_positions_admin_product_variants_path(@product) %>">
    <thead data-hook="variants_header">
      <tr>
        <th colspan="2"><%= Spree.t(:options) %></th>
        <th><%= Spree.t(:price) %></th>
        <th><%= Spree.t(:sku) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @variants.each do |variant| %>
      <tr id="<%= spree_dom_id variant %>" <%= 'style="color:red;"' if variant.deleted? %> data-hook="variants_row">
        <td class="move-handle">
          <% if can? :edit, variant %>
            <span class="icon icon-move handle"></span>
          <% end %>
        </td>
        <td><%= variant.options_text %></td>
        <td><%= variant.display_price.to_html %></td>
        <td><%= variant.sku %></td>
        <td class="actions actions-2 text-right">
          <%= link_to_edit(variant, :no_text => true) if can?(:edit, variant) && !variant.deleted? %>
          <%= link_to_delete(variant, :no_text => true) if can?(:destroy, variant) && !variant.deleted? %>
        </td>
      </tr>
      <% end %>
      <% unless @product.has_variants? %>
        <tr>
          <td colspan="5"><%= Spree.t(:none) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found alert alert-info">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Variant)) %>,
    <%= link_to(Spree.t(:add_one), spree.new_admin_product_variant_path(@product)) if can? :create, Spree::Variant %>!
  </div>
<% end %>

<% if @product.empty_option_values? %>
  <% if can?(:create, Spree::OptionType) && can?(:create, Spree::OptionValue) %>
    <p class='first_add_option_types no-objects-found' data-hook="first_add_option_types">
      <%= Spree.t(:to_add_variants_you_must_first_define) %>
      <%= link_to(Spree.t(:option_types), spree.admin_product_url(@product)) %>
      <%= Spree.t(:and) %>
      <%= link_to Spree.t(:option_values), spree.admin_option_types_url %>
    </p>
  <% end %>
<% else %>
  <% content_for :page_actions do %>
    <%= button_link_to(Spree.t(:new_variant), spree.new_admin_product_variant_url(@product), { :remote => :true, :icon => 'add', :'data-update' => 'new_variant', :class => 'btn-success', id: 'new_var_link' }) if can? :create, Spree::Variant %>
    <%= button_link_to (@deleted.blank? ? Spree.t(:show_deleted) : Spree.t(:show_active)), spree.admin_product_variants_url(@product, :deleted => @deleted.blank? ? "on" : "off"), { :class => 'btn-default', :icon => 'filter' } %>
  <% end %>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/new.html.erb
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <div class="well">
    <fieldset data-hook="admin_variant_new_form">
      <legend><%= Spree.t(:new_variant) %></legend>
      <%= render :partial => 'form', :locals => { :f => f } %>
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </fieldset>
  </div>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/variants/new.js.erb
$("#new_variant").html('<%= escape_javascript(render template: 'spree/admin/variants/new', formats: [:html], handlers: [:erb]) %>');
$(".select2").select2();
$("#new_var_link").hide();