shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    get '/variants/search', to: "variants#search", as: :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_authorization_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :tax_rates

    resources :trackers
    resources :payment_methods
    resources :roles

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
    end
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/controllers/spree/admin/products_controller.rb
module Spree
  module Admin
    class ProductsController < ResourceController
      helper 'spree/products'

      before_action :load_data, except: :index
      create.before :create_before
      update.before :update_before
      helper_method :clone_object_url

      def show
        session[:return_to] ||= request.referer
        redirect_to action: :edit
      end

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def update
        if params[:product][:taxon_ids].present?
          params[:product][:taxon_ids] = params[:product][:taxon_ids].split(',')
        end
        if params[:product][:option_type_ids].present?
          params[:product][:option_type_ids] = params[:product][:option_type_ids].split(',')
        end
        invoke_callbacks(:update, :before)
        if @object.update_attributes(permitted_resource_params)
          invoke_callbacks(:update, :after)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_save }
            format.js   { render layout: false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to
          # update the product again
          @product.slug = @product.slug_was if @product.slug.blank?
          invoke_callbacks(:update, :fails)
          respond_with(@object)
        end
      end

      def destroy
        @product = Product.friendly.find(params[:id])
        @product.destroy

        flash[:success] = Spree.t('notice_messages.product_deleted')

        respond_with(@product) do |format|
          format.html { redirect_to collection_url }
          format.js  { render_js_for_destroy }
        end
      end

      def clone
        @new = @product.duplicate

        if @new.save
          flash[:success] = Spree.t('notice_messages.product_cloned')
        else
          flash[:error] = Spree.t('notice_messages.product_not_cloned')
        end

        redirect_to edit_admin_product_url(@new)
      end

      def stock
        @variants = @product.variants.includes(*variant_stock_includes)
        @variants = [@product.master] if @variants.empty?
        @stock_locations = StockLocation.accessible_by(current_ability, :read)
        if @stock_locations.empty?
          flash[:error] = Spree.t(:stock_management_requires_a_stock_location)
          redirect_to admin_stock_locations_path
        end
      end

      protected

      def find_resource
        Product.with_deleted.friendly.find(params[:id])
      end

      def location_after_save
        spree.edit_admin_product_url(@product)
      end

      def load_data
        @taxons = Taxon.order(:name)
        @option_types = OptionType.order(:name)
        @tax_categories = TaxCategory.order(:name)
        @shipping_categories = ShippingCategory.order(:name)
      end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:deleted_at_null] ||= "1"

        params[:q][:s] ||= "name asc"
        @collection = super
        if params[:q].delete(:deleted_at_null) == '0'
          @collection = @collection.with_deleted
        end
        # @search needs to be defined as this is passed to search_form_for
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
              distinct_by_product_ids(params[:q][:s]).
              includes(product_includes).
              page(params[:page]).
              per(params[:per_page] || Spree::Config[:admin_products_per_page])

        @collection
      end

      def create_before
        return if params[:product][:prototype_id].blank?
        @prototype = Spree::Prototype.find(params[:product][:prototype_id])
      end

      def update_before
        # note: we only reset the product properties if we're receiving a post
        #       from the form on that tab
        return unless params[:clear_product_properties]
        params[:product] ||= {}
      end

      def product_includes
        [{ variants: [:images], master: [:images, :default_price] }]
      end

      def clone_object_url(resource)
        clone_admin_product_url resource
      end

      private

      def variant_stock_includes
        [:images, stock_items: :stock_location, option_values: :option_type]
      end
    end
  end
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/helpers/spree/admin/products_helper.rb
module Spree
  module Admin
    module ProductsHelper
      def taxon_options_for(product)
        options = @taxons.map do |taxon|
          selected = product.taxons.include?(taxon)
          content_tag(:option,
                      :value    => taxon.id,
                      :selected => ('selected' if selected)) do
            (taxon.ancestors.pluck(:name) + [taxon.name]).join(" -> ")
          end
        end.join("").html_safe
      end

      def option_types_options_for(product)
        options = @option_types.map do |option_type|
          selected = product.option_types.include?(option_type)
          content_tag(:option,
                      :value    => option_type.id,
                      :selected => ('selected' if selected)) do
            option_type.name
          end
        end.join("").html_safe
      end
    end
  end
end

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/products/_add_stock_form.html.erb
<div class="panel-heading">
  <h1 class="panel-title">
    <%= Spree.t(:add_stock_management) %>
  </h1>
</div>
<div class="panel-body">
  <%= form_for [:admin, Spree::StockMovement.new], url: admin_stock_items_path do |f| %>
    <div data-hook="admin_stock_movements_form_fields" class="row">
      <div class="col-md-2">
        <div class="form-group">
          <%= f.field_container :quantity do %>
            <%= f.label :quantity, Spree.t(:quantity) %>
            <%= f.number_field :quantity, class: 'form-control', value: 1 %>
          <% end %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.field_container :stock_location do %>
            <%= label_tag :stock_location_id, Spree.t(:stock_location) %>
            <%= select_tag 'stock_location_id', options_from_collection_for_select(@stock_locations, :id, :name),
              class: 'select2' %>
          <% end %>
        </div>
      </div>

      <div class="col-md-5">
        <div class="form-group">
          <%= f.field_container :variant_id do %>
            <%= label_tag 'variant_id', Spree.t(:variant) %>
            <%= select_tag 'variant_id', options_from_collection_for_select(@variants, :id, :sku_and_options_text),
              class: 'select2' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-actions text-center" data-hook="buttons">
      <%= button Spree.t(:add_stock), 'plus' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), collection_url, :icon => 'delete' %>
    </div>
  <% end %>
</div>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/products/_autocomplete.js.erb
<script type='text/template' id='product_template'>
  <li id='product_{{ product.id }}' data-product-id='{{ product.id }}' data-taxons="{{ product.taxon_ids }}" class='product'>
    <a class="sort-handle js-sort-handle"><span class="icon icon-move"></span></a>
    <div class="btn-group">
      <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" data-hook="taxon_product_dropdown">
        <li><a href="javascript:;" class="edit-product js-edit-product"><%= Spree.t(:edit) %></a></li>
        <li><a href="javascript:;" class="delete-product js-delete-product"><%= Spree.t(:delete_from_taxon) %></a></li>
      </ul>
    </div>
    <div class='image'>
      {{#if product.image }}
        <img src='{{product.image}}' alt='{{ product.name }}' class='thumbnail' />
      {{ else }}
        <img src='<%= image_path("noimage/small.png") %>' alt='{{product.name }}' class='thumbnail' />
      {{/if}}
    </div>
    <div class="product-info">
      <div class="name">{{ product.name }}</div>
      <div class="price">{{ product.display_price }}</div>
    </div>
  </li>
</script>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/products/_form.html.erb
<div data-hook="admin_product_form_fields">

  <div class="row">

    <div class="col-md-8" data-hook="admin_product_form_left">
      <div data-hook="admin_product_form_name">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', class: 'required')) %>
          <%= f.text_field :name, class: 'form-control title' %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_slug">
        <%= f.field_container :slug, class: ['form-group'] do %>
          <%= f.label :slug, raw(Spree.t(:slug) + content_tag(:span, ' *', class: "required")) %>
          <%= f.text_field :slug, class: 'form-control title' %>
          <%= f.error_message_on :slug %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_description">
        <%= f.field_container :description, class: ['form-group'] do %>
          <%= f.label :description, Spree.t(:description) %>
          <%= f.text_area :description, { rows: "#{unless @product.has_variants? then '20' else '13' end}", class: 'form-control' } %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4" data-hook="admin_product_form_right">
      <div data-hook="admin_product_form_price">
        <%= f.field_container :price, class: ['form-group'] do %>
          <%= f.label :price, raw(Spree.t(:master_price) + content_tag(:span, ' *', class: "required")) %>
          <%= f.text_field :price, value: number_to_currency(@product.price, unit: ''), class: 'form-control', disabled: (cannot? :update, Spree::Price) %>
          <%= f.error_message_on :price %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_cost_price" class="alpha two columns">
        <%= f.field_container :cost_price, class: ['form-group'] do %>
          <%= f.label :cost_price, Spree.t(:cost_price) %>
          <%= f.text_field :cost_price, value: number_to_currency(@product.cost_price, unit: ''), class: 'form-control' %>
          <%= f.error_message_on :cost_price %>
        <% end %>
      </div>
      <div data-hook="admin_product_form_cost_currency" class="omega two columns">
        <%= f.field_container :cost_currency, class: ['form-group'] do %>
          <%= f.label :cost_currency, Spree.t(:cost_currency) %>
          <%= f.text_field :cost_currency, class: 'form-control' %>
          <%= f.error_message_on :cost_currency %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_available_on">
        <%= f.field_container :available_on, class: ['form-group'] do %>
          <%= f.label :available_on, Spree.t(:available_on) %>
          <%= f.error_message_on :available_on %>
          <%= f.text_field :available_on, value: datepicker_field_value(@product.available_on), class: 'datepicker form-control' %>
        <% end %>
      </div>

      <% if @product.has_variants? %>
        <div data-hook="admin_product_form_multiple_variants" class="well">
          <%= f.label :skus, Spree.t(:sku).pluralize %>
          <div class="info marginb">
            <%= Spree.t(:info_product_has_multiple_skus, count: @product.variants.count) %>
            <ul class="text_list">
              <% @product.variants.first(5).each do |variant| %>
                <li><%= variant.sku %></li>
              <% end %>
            </ul>
            <% if @product.variants.count > 5 %>
              <em>
                <%= Spree.t(:info_number_of_skus_not_shown, count: @product.variants.count - 5) %>
              </em>
            <% end %>
          </div>
          <div class="info-actions">
            <% if can?(:admin, Spree::Variant) %>
              <%= link_to_with_icon 'variants', 'Manage Variants', spree.admin_product_variants_url(@product), class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div data-hook="admin_product_form_sku">
          <%= f.field_container :sku, class: ['form-group'] do %>
            <%= f.label :sku, Spree.t(:sku) %>
            <%= f.text_field :sku, size: 16, class: 'form-control' %>
          <% end %>
        </div>

        <div id="shipping_specs" class="row">
          <div class="col-md-6">
            <div id="shipping_specs_weight_field" data-hook="admin_product_form_weight" class="form-group">
              <%= f.label :weight, Spree.t(:weight) %>
              <%= f.text_field :weight, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_height_field" data-hook="admin_product_form_height" class="form-group">
              <%= f.label :height, Spree.t(:height) %>
              <%= f.text_field :height, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_width_field" data-hook="admin_product_form_width" class="form-group">
              <%= f.label :width, Spree.t(:width) %>
              <%= f.text_field :width, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_depth_field" data-hook="admin_product_form_depth" class="form-group">
              <%= f.label :depth, Spree.t(:depth) %>
              <%= f.text_field :depth, size: 4, class: 'form-control' %>
            </div>
          </div>
        </div>
      <% end %>

      <div data-hook="admin_product_form_shipping_categories">
        <%= f.field_container :shipping_categories, class: ['form-group'] do %>
          <%= f.label :shipping_category_id, Spree.t(:shipping_categories) %>
          <%= f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', disabled: (cannot? :edit, Spree::ShippingCategory) }) %>
          <%= f.error_message_on :shipping_category %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_tax_category">
        <%= f.field_container :tax_category, class: ['form-group'] do %>
          <%= f.label :tax_category_id, Spree.t(:tax_category) %>
          <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', disabled: (cannot? :edit, Spree::TaxCategory) }) %>
          <%= f.error_message_on :tax_category %>
        <% end %>
      </div>
    </div>

  </div>

  <div data-hook="admin_product_form_taxons">
    <%= f.field_container :taxons, class: ['form-group'] do %>
      <%= f.label :taxon_ids, Spree.t(:taxons) %>

      <% if can? :modify, Spree::Classification %>
        <%= f.hidden_field :taxon_ids, value: @product.taxon_ids.join(',') %>
      <% elsif @product.taxons.any? %>
        <ul class="text_list">
          <% @product.taxons.each do |taxon| %>
            <li><%= taxon.name %></li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :taxons) %></div>
      <% end %>

    <% end %>
  </div>

  <div data-hook="admin_product_form_option_types">
    <%= f.field_container :option_types, class: ['form-group'] do %>
      <%= f.label :option_type_ids, Spree.t(:option_types) %>

      <% if can? :modify, Spree::OptionType %>
        <%= f.hidden_field :option_type_ids, value: @product.option_type_ids.join(',') %>
      <% elsif @product.option_types.any? %>
        <ul class="text_list">
          <% @product.option_types.each do |type| %>
            <li><%= type.presentation %> (<%= type.name %>)</li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :option_types) %></div>
      <% end %>

    <% end %>
  </div>


<div data-hook="admin_product_form_meta">

  <div data-hook="admin_product_form_meta_keywords">
    <%= f.field_container :meta_keywords, class: ['form-group'] do %>
      <%= f.label :meta_keywords, Spree.t(:meta_keywords) %>
      <%= f.text_field :meta_keywords, class: 'form-control' %>
    <% end %>
  </div>

  <div data-hook="admin_product_form_meta_description">
    <%= f.field_container :meta_description, class: ['form-group'] do %>
      <%= f.label :meta_description, Spree.t(:meta_description) %>
      <%= f.text_field :meta_description, class: 'form-control' %>
    <% end %>
  </div>

  <div data-hook="admin_product_form_additional_fields"></div>

</div>

<% unless Rails.env.test? %>
  <script>
    $('.select2-container').css();
  </script>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/products/_properties_form.erb
<% content_for :page_title do %>
  <%= Spree.t(:properties) %>
<% end %>

<% f.fields_for :product_properties do |properties_form| %>
    <div data-hook="value">
      <%= properties_form.label :value, properties_form.object.property.presentation %>
      <%= properties_form.text_field :value, :class => "form-control" %>
    </div>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/products/edit.html.erb
<% content_for :page_actions do %>
  <% if can?(:create, Spree::Product) %>
    <%= button_link_to Spree.t(:new_product), new_object_url, { :class => "btn-success", :icon => 'add', :id => 'admin_new_product' } %>
  <% end %>
<% end %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Product Details' } %>
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @product } %>

<%= form_for [:admin, @product], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/products/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Product) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_product), new_object_url, { :class => "btn-success", :icon => 'add', :id => 'admin_new_product' } %>
<% end if can?(:create, Spree::Product) %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {:f => f} %>
      <div data-hook="admin_products_index_search" class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, :size => 15, class: "form-control js-quick-search-target" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
            <%= f.text_field :variants_including_master_sku_cont, :size => 15, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="field checkbox">
            <label>
              <%= f.check_box :deleted_at_null, {:checked => params[:q][:deleted_at_null] == '0'}, '0', '1' %>
              <%= Spree.t(:show_deleted) %>
            </label>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>

  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @collection.any? %>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:sku) %></th>
        <th colspan="2"><%= sort_link @search,:name, Spree.t(:name), { default_order: "desc" }, {title: 'admin_products_listing_name_title'} %></th>
        <th class="text-center">
          <%= sort_link @search, :master_default_price_amount, Spree.t(:master_price), {}, {title: 'admin_products_listing_price_title'} %>
        </th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="sku"><%= product.sku rescue '' %></td>
            <td class="image"><%= mini_image product %></td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="text-center"><%= product.display_price.to_html rescue '' %></td>
            <td class="actions actions-3 text-right" data-hook="admin_products_index_row_actions">
              <%= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
              <%= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
              <%= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Product)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

shared/bundle/ruby/2.2.0/gems/spree_backend-3.0.0/app/views/spree/admin/products/stock.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Stock Management' } %>
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @product } %>

<% if can? :create, Spree::StockMovement %>
  <div id="add_stock_form" class="panel panel-default">
    <%= render 'add_stock_form' %>
  </div>
<% end %>

<div class="panel panel-default">
  <table class="table table-bordered" id="listing_product_stock">
    <thead>
      <tr data-hook="admin_product_stock_management_index_headers">
        <th colspan="2"><%= Spree.t(:variant) %></th>
        <th colspan="3"><%= Spree.t(:stock_location_info) %></th>
      </tr>
    </thead>
    <tbody>
      <% @variants.each do |variant| %>
        <% if variant.stock_items.present? %>
          <tr id="<%= spree_dom_id variant %>" data-hook="admin_product_stock_management_index_rows">
            <td class="image text-center">
              <% if variant.images.present? %>
                <%= image_tag variant.images.first.attachment.url(:mini) %>
              <% end %>
            </td>
            <td>
              <%= variant.sku_and_options_text %>
              <%= form_tag admin_product_variants_including_master_path(@product, variant, format: :js), method: :post, class: 'toggle_variant_track_inventory' do %>
                <div class="checkbox">
                  <%= label_tag :track_inventory do %>
                    <%= check_box_tag 'track_inventory', 1, variant.track_inventory?,
                                      class: 'track_inventory_checkbox' %>
                    <%= Spree.t(:track_inventory) %>
                  <% end %>
                </div>
                <%= hidden_field_tag 'variant[track_inventory]', variant.track_inventory?,
                    class: 'variant_track_inventory',
                    id: "variant_track_inventory_#{variant.id}" %>
              <% end if can?(:update, @product) && can?(:update, variant) %>
            </td>

            <td colspan="3" class="stock_location_info">
              <table class="table table-bordered no-marginb">
                <thead>
                  <th><%= Spree.t(:stock_location) %></th>
                  <th class="text-center"><%= Spree.t(:count_on_hand) %></th>
                  <th class="text-center"><%= Spree.t(:backorderable) %></th>
                  <th class="actions text-center"></th>
                </thead>
                <tbody>
                  <% variant.stock_items.each do |item| %>
                    <% next unless @stock_locations.include?(item.stock_location) %>
                    <tr id="stock-item-<%= item.id %>">
                      <td><%= item.stock_location.name %></td>
                      <td class="text-center"><%= item.count_on_hand %></td>
                      <td class="text-center">
                        <%= form_tag admin_stock_item_path(item), method: :put, class: 'toggle_stock_item_backorderable' do %>
                          <%= check_box_tag 'stock_item[backorderable]', true,
                                item.backorderable?,
                                class: 'stock_item_backorderable',
                                id: "stock_item_backorderable_#{item.stock_location.id}" %>
                        <% end if can? :update, item %>
                      </td>
                      <td class="actions actions-1 text-center">
                        <%= link_to_with_icon('delete', Spree.t(:remove), [:admin, item], method: :delete, remote: true, class: 'icon_link btn btn-danger btn-sm', data: { action: :remove, confirm: Spree.t(:are_you_sure) }, no_text: true) if can? :destroy, item %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>